### ISSUE TITLE
Multiplayer Crashing

### ISSUE THREAD

**Issue by PandeTheGamerYT** [werty1124/SimpleMagnet#7]
Error : 
`java.lang.NoClassDefFoundError: baubles/common/lib/PlayerHandler
	at werty.simplemagnet.SEventHandler.itemTossed(SEventHandler.java:28)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_525_SEventHandler_itemTossed_ItemTossEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.common.ForgeHooks.onPlayerTossEvent(ForgeHooks.java:603)
	at net.minecraft.entity.player.EntityPlayer.func_71019_a(EntityPlayer.java:729)
	at net.minecraft.inventory.Container.func_75134_a(Container.java:534)
	at net.minecraft.inventory.ContainerPlayer.func_75134_a(ContainerPlayer.java:100)
	at net.minecraft.entity.player.EntityPlayer.func_70106_y(EntityPlayer.java:1480)
	at net.minecraft.world.World.func_72900_e(World.java:1166)
	at net.minecraft.server.management.PlayerList.func_72367_e(PlayerList.java:403)
	at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:804)
	at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:451)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:213)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)`

Hope this will be fixed!

**Comment by werty1124** [comment]
Late reply but hopefully should be resolved
